Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vbguest.auto_update = false

  # vm1
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.33.10"
    vm1.vm.provider "virtualbox" do |vb1|
      vb1.memory = "1024"
      vb1.cpus = "1"
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install httpd -y
    systemctl start httpd
    systemctl enable httpd
  SHELL

  # vm2
  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.33.11"
    vm2.vm.provider "virtualbox" do |vb2|
      vb2.memory = "1024"
      vb2.cpus = "1"
    end
  end 
end
